databases:
  - name: practice_app
    databaseName: practice_db
    user: triciasykes

services:
  - type: web
    name: practice_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: practice_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false